### ISSUE TITLE
How to read data uri js value on rails?

### ISSUE THREAD

**Issue by pailoro** [timsly/carrierwave-data-uri#10]
If I generate the data_uri on javascript, with webcamjs for example, how can I pass the value to rails to upload the file?

**Comment by timfjord** [comment]
data URI is a normal string, so the easiest way to pass it to the rails is to assign to, say, some hidden field and submit the form.

``` javascript
Webcam.snap(function(data_uri) {
  $('#image_data_uri').val(data_uri); 
  $('form').submit();
});
```

And then, on back-end side, read and process this value.

``` ruby
user = User.find 123
user.image_data_uri = params[:image_data_uri]
user.save
```

**Comment by pailoro** [comment]
Thanks! =D
