### ISSUE TITLE
Upload to Cloudinary

### ISSUE THREAD

**Issue by pailoro** [timsly/carrierwave-data-uri#11]
Hi,

I have a functin to upload a data uri that works fine, but when I upload it to heroku and start to use Cloudinary, the image record comes empty.

```
def upload_image
    photo = params[:picture][:photo]  
    @picture = Picture.new(picture_params)
    @picture.photo_data_mimetype = 'image/jpeg'
    @picture.user_id = current_user.id 
    @picture.photo = photo
    @picture.save
  end
```

The gem its not working with cloudinary integration yet?

Thanks!

**Comment by timfjord** [comment]
Hi @pailoro 
This gem is just a data uri parser.
In a few words it converts string to file.
But everything else related to file upload is handled by carrierwave.
So you should rather check carrierwave cloudinary integration setup

**Comment by timfjord** [comment]
Closing this one for now. Feel free to reopen if issue still exists
