### ISSUE TITLE
How does it work in view/form

### ISSUE THREAD

**Issue by Rubioli** [timsly/carrierwave-data-uri#12]
Great `gem`.

When I tried it from my `rails console`, everything works fine. But when I implement to my `view` or `controller` I get error: `undefined method image_data_uri= for nil:NilClass`

This is how I did it:
**Form view:**
`= f.text_field :image_data_uri`

**Saving only from controller without controller**

```
before_action :save_data_uri, only: [:create]
def save_data_uri
      @album.image_data_uri = "data:image/gif;base64,R0lGODlhAQABAJEAAAAAAP////8AAP///yH5BAEAAAMALAAAAAABAAEAAAICVAEAOw=="
      @album.save
end
```

I need to do it from my `view` and looking for a solution for my `form`.
Hope you can help me figure it out.

**Comment by timfjord** [comment]
Hi @Rubioli 
It seems that you didn't set `@album` variable, that's why you got this error.

**Comment by Rubioli** [comment]
Thanks @timsly
