### ISSUE TITLE
Can I use when `create`.

### ISSUE THREAD

**Issue by kntmrkm** [timsly/carrierwave-data-uri#3]
I tried that works by save method.

But, `create` method cat not save `datauri'.

Can it?

**Comment by kntmrkm** [comment]
`update` in controller does not work also.

**Comment by timfjord** [comment]
Thanks @kntmrkm 
I will take a look to this issue

**Comment by kntmrkm** [comment]
thanks.

**Comment by timfjord** [comment]
@kntmrkm i just added specs where i covered `create` and `update` methods. See [here](https://github.com/timsly/carrierwave-data-uri/blob/4e25889173caf7b25f2779d97993b230cf939f2e/spec/integration_spec.rb)
All specs are passing
So please check your setup, maybe you missed something

**Comment by kntmrkm** [comment]
Sorry my misunderstand and delay.
It works well. thanks.

and sorry again.
